---
title: "Create CCES data set with ACS"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{1_CCES_ACS}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

######## <!-- process cces -->

```{r unzip_cces}
# NEW: can't distribute CCES Stata files via github unless compressed ----
dir.create(here::here("data", "cces", "main")) # may always be superfluous

cces <- dir("data/cces/zip", full.names = TRUE)
cces <- `names<-`(cces, stringr::str_extract(cces, "\\d+"))
cces <- as.list(cces)
cces <- dplyr::as_tibble(cces)
cces <- tidyr::gather(cces, "year", "zipfile")
cces <- dplyr::group_by(cces, .data$year)

cces <- dplyr::transmute(cces, filename = unzip(dplyr::first(.data$zipfile),
                                                exdir = here::here("data", "cces", "main")))
```
```{r ingest_cces}
cces <- dplyr::transmute(cces, data = list(haven::read_dta(dplyr::first(.data$filename))))
```
```{r pull_cols_cces}
# find the right column IDs for the variables we want each year ----
# and select those columns from the year's data
cols <- readr::read_csv("data/cces/columns.csv") # constructed by hand from the yearly codebooks
cols <- tidyr::gather(cols, "year", "colname", -.data$var)
cols <- dplyr::filter_all(cols, function(i) {!is.na(i)})
cols <- dplyr::group_by(cols, .data$year)
cols <- dplyr::summarise(cols, cols = list(`names<-`(.data$colname, .data$var)))
cols <- dplyr::group_by(cols, .data$year)
cols <- dplyr::mutate(cols, cols = list(as.list(dplyr::first(.data$cols))))
cols <- dplyr::left_join(cols, cces)
cols <- dplyr::mutate(cols, data = list(
  do.call(dplyr::select, c(list(.data = dplyr::first(.data$data)), dplyr::first(.data$cols)))
))
```
```{r mend_cols_cces}
# iron out trivial differences in factor labels across years ----
# otherwise they won't tidyr::unnest() together
cols <- dplyr::mutate(cols, data = list(dplyr::mutate_if(dplyr::first(.data$data), haven::is.labelled, function(x) {
  `attr<-`(x, "labels", `names<-`(attr(x, "labels", TRUE), stringr::str_to_lower(names(attr(x, "labels", TRUE)))))
})))
cols <- dplyr::mutate(cols, data = list(dplyr::mutate_if(dplyr::first(.data$data), haven::is.labelled, function(x) {
  `attr<-`(x, "labels", `names<-`(attr(x, "labels", TRUE), stringr::str_trim(names(attr(x, "labels", TRUE)))))
})))
cols <- dplyr::mutate(cols, data = list(dplyr::mutate_if(dplyr::first(.data$data), haven::is.labelled, function(x) {
  `attr<-`(x, "labels", `names<-`(attr(x, "labels", TRUE), stringr::str_replace_all(names(attr(x, "labels", TRUE)), "  +", " ")))
})))

# for these columns labels differ across years but levels do not; attach labels later ----
cols <- dplyr::mutate(cols, data = list(dplyr::mutate_if(dplyr::first(.data$data), 
                                                         colnames(dplyr::first(.data$data)) %in% c("dd_months_in_city",
                                                                                                   "dd_years_in_city",
                                                                                                   "dd_national_economy",
                                                                                                   "dd_residency",
                                                                                                   "dd_union_family",
                                                                                                   "dd_union_self",
                                                                                                   "ww_weight",
                                                                                                   "vv_weight",
                                                                                                   "dd_county_fips",
                                                                                                   "dd_zip",
                                                                                                   "pp_attend_meeting",
                                                                                                   "pp_campaign_work",
                                                                                                   "pp_post_sign"), as.numeric)))

# make factors -- levels should now be compatible? ----
cols <- dplyr::mutate(cols, data = list(dplyr::mutate_if(dplyr::first(.data$data), haven::is.labelled, haven::as_factor)))

# coerce just a couple to character ----
cols <- dplyr::mutate(cols, data = list(dplyr::mutate_if(dplyr::first(.data$data), 
                                                         colnames(dplyr::first(.data$data)) %in% c("dd_state", 
                                                                                                   # "dd_zip",
                                                                                                   "dd_county_name",
                                                                                                   "dd_party_reg",
                                                                                                   "vv_party_reg"), as.character)))
# cols <- dplyr::mutate(cols, data = list(dplyr::mutate_if(dplyr::first(.data$data),
#                                                          colnames(dplyr::first(.data$data)) == "dd_zip",
#                                                          as.numeric)))
cols <- dplyr::mutate(cols, data = list(dplyr::mutate_if(dplyr::first(.data$data),
                                                         colnames(dplyr::first(.data$data)) == "vv_party_reg",
                                                         stringr::str_to_lower)))
```
```{r unnest_cols_cces}
# unnest the data ----
set <- dplyr::select(cols, -.data$cols)
set <- tidyr::unnest(set,  .data$data)

# eliminate categories that aren't meaningful ----
set <- dplyr::mutate_if(set, is.factor, function(x) { # set non-substantive answers to NA
  factor(x, levels = setdiff(levels(x), c("skipped", "not asked", "prefer not to say", "not sure")))
})
set <- dplyr::mutate_at(set, "dd_income_new", function(x) { # a few folks were given bogus categories for dd_income_new
  factor(x, levels = setdiff(levels(x), c("$150,000 or more", "$250,000 or more")))
})

# eliminate no-good numeric values ----
set <- dplyr::mutate(set, 
                     dd_residency      = ifelse(.data$dd_residency      == 7,  6, .data$dd_residency),
                     dd_years_in_city  = ifelse(.data$dd_years_in_city  <  0, NA, .data$dd_years_in_city),
                     dd_months_in_city = ifelse(.data$dd_months_in_city <  0, NA, .data$dd_months_in_city))

# insert levels for factors whose levels differed substantially across years ----
set <- dplyr::mutate(set,
                     dd_union_family     = factor(.data$dd_union_family,     levels = 1:3, labels = c("is", "was", "no")),
                     dd_union_self       = factor(.data$dd_union_self,       levels = 1:3, labels = c("is", "was", "no")),
                     pp_attend_meeting   = factor(.data$pp_attend_meeting,   levels = 1:2, labels = c("yes", "no")),
                     pp_campaign_work    = factor(.data$pp_campaign_work,    levels = 1:2, labels = c("yes", "no")),
                     pp_post_sign        = factor(.data$pp_post_sign,        levels = 1:2, labels = c("yes", "no")),
                     dd_national_economy = factor(.data$dd_national_economy, levels = 1:5, labels = c("much better",
                                                                                                      "better",
                                                                                                      "about the same",
                                                                                                      "worse",
                                                                                                      "much worse")),
                     dd_residency        = factor(.data$dd_residency,        levels = 1:6, labels = c("under 1 month",
                                                                                                      "1 to 6 months",
                                                                                                      "7 to 11 months",
                                                                                                      "1 to 2 years",
                                                                                                      "3 to 4 years",
                                                                                                      "5 or more years")))

# disentangle self-reported party registration ----
set <- dplyr::mutate(set,
                     dd_democratic  = sapply(stringr::str_detect(.data$dd_party_reg, "^dem"),              isTRUE),
                     dd_republican  = sapply(stringr::str_detect(.data$dd_party_reg, "^rep"),              isTRUE),
                     dd_third_party = sapply(stringr::str_detect(.data$dd_party_reg, "(green|lib|other)"), isTRUE),
                     dd_no_party    = !(.data$dd_democratic | .data$dd_republican | .data$dd_third_party))

# disentangle validated party registration ----
set <- dplyr::mutate(set, vv_party_reg = factor(.data$vv_party_reg, levels = setdiff(unique(.data$vv_party_reg), "")))
set <- dplyr::mutate(set,
                     vv_democratic  = (.data$vv_party_reg == "dem"),
                     vv_republican  = (.data$vv_party_reg == "rep"),
                     vv_unk_party   = (.data$vv_party_reg == "unk"),
                     vv_independent = (.data$vv_party_reg == "ind"),
                     vv_third_party = !(.data$vv_democratic | .data$vv_republican | .data$vv_unk_party | .data$vv_independent))

# standardize citizenship and union status ----
set <- dplyr::mutate(set,
                     dd_citizen        = ifelse(is.na(.data$dd_citizenship_old),
                                                .data$dd_citizenship_new == "yes",
                                                .data$dd_citizenship_old != "immigrant non-citizen"),
                     dd_union_self_now = ifelse(is.na(.data$dd_union_self),
                                                as.numeric(.data$dd_union_either) %in% c(2, 4),
                                                .data$dd_union_self == "is"),
                     dd_union_self_now = ifelse(is.na(.data$dd_union_family),
                                                as.numeric(.data$dd_union_either) %in% c(3, 4),
                                                .data$dd_union_family == "is"))
```
```{r process_counties_cces}
# smash in county IDs from the cumulative file b/c they are missing in the 2017 file ----
cml <- readRDS(here::here("data", "cces", "cumulative_2006_2018.Rds"))
cml <- dplyr::filter(cml, .data$year == 2017)
cml <- dplyr::select(cml, dd_case_id = .data$case_id, dd_real_county_fips = .data$county_fips)
cml <- dplyr::mutate_all(cml, as.numeric)
set <- dplyr::left_join(set, cml)
set <- dplyr::mutate(set, dd_county_fips = ifelse(is.na(.data$dd_real_county_fips), .data$dd_county_fips, .data$dd_real_county_fips))

# standardize 3-digit county FIPS to omit leading 2-digit state FIPS ----
set <- dplyr::mutate(set, dd_county_fips = .data$dd_county_fips %% 1000)
```
```{r save_set}
saveRDS(set, here::here("data", "cces.rds"))
```

######## <!-- process acs -->

```{r init_acs}
# Registering and installing a Census API key is required
# go to https://api.census.gov/data/key_signup.html to get one if you don't have it
# then enter tidycensus::census_api_key("<your key>", install=TRUE) to install your key

# variables ----
# urban/rural can be obtained only from the 2010 census
act <- c(n       = "B02001_001", # tract-level variables
         n_white = "B02001_002",
         n_black = "B02001_003",
         w_poor  = "B17001A_002",
         w_other = "B17001A_031",
         n_poor  = "B17001_002",
         n_other = "B17001_031")
acc <- c(m_indus = "C24030_002", # county-level variables
         f_indus = "C24030_029",
         m_manuf = "C24030_007",
         f_manuf = "C24030_034")

# table of state-years ----
# TODO: cleanly separate ACS and CCES parts into two files
acs <- dplyr::group_by(set)
acs <- dplyr::select(acs, .data$year, .data$dd_state)
acs <- dplyr::group_by_all(acs)
acs <- dplyr::summarise(acs)
acs <- dplyr::filter(acs, .data$year > 2008)
acs <- dplyr::group_by_all(acs)

# download county-level vars ----
system.time({
  acs <- dplyr::mutate(acs, county_pop = list(tidycensus::get_acs("county",
                                                                  acc,
                                                                  year  = as.numeric(dplyr::first(.data$year)),
                                                                  state = dplyr::first(.data$dd_state))))
})

# prod county-level cars into shape and group by county-year ----
acs <- tidyr::unnest(acs)
acs <- dplyr::select(acs, -.data$moe)
acs <- tidyr::spread(acs, .data$variable, .data$estimate)
acs <- dplyr::rename(acs,
                     dd_county_fips = .data$GEOID,
                     dd_county_name = .data$NAME)
acs <- dplyr::mutate(acs, dd_county_fips = as.numeric(.data$dd_county_fips) %% 1000)
acs <- dplyr::mutate(acs, dd_county_name = stringr::str_remove(.data$dd_county_name, 
                                                               paste(",", stringr::str_to_title(.data$dd_state))))
acs <- dplyr::mutate(acs, dd_county_name = stringr::str_remove(.data$dd_county_name, ", District of Columbia"))
acs <- dplyr::group_by(acs, .data$year, .data$dd_state, .data$dd_county_fips, .data$dd_county_name)
```
```{r download_acs_more}
# tract-level data are where segregation stats come from ----
# download tract-level vars by county-year and _save_ ----
dir.create(here::here("data", "cces", "tract"))

# this may error out unexpectedly while downloading. Just restart it
foo <- function(yr, st, id) {
  fn <- paste0(here::here("data", "cces", "tract"), "/", paste0(c(yr, st, id), collapse="_"), ".rds")
  
  if(file.exists(fn)) {} else {ds <- tidycensus::get_acs("tract", act, year = yr, state = st, county = id)}
  if(file.exists(fn)) {} else {saveRDS(ds, fn)}
  
  fn
}

system.time(acr <- dplyr::mutate(acs, tract = foo(as.numeric(.data$year), .data$dd_state, .data$dd_county_fips)))
```
```{r reload_acs}
# reload tract-level vars ----
system.time(acr <- dplyr::transmute(acr, tract = list(readRDS(dplyr::first(.data$tract)))))
system.time(acr <- dplyr::group_modify(acr, function(.x, .y) {dplyr::first(.x$tract)})) # far faster than using tidyr::unnest

acr <- dplyr::select(acr, -.data$moe, -.data$NAME)
acr <- tidyr::spread(acr, .data$variable, .data$estimate)

# compute derived county-level values ----
acr <- dplyr::summarise(acr,
                        pct_white_tot  = sum(.data$n_white) / sum(.data$n),
                        pct_black_tot  = sum(.data$n_black) / sum(.data$n),
                        pct_white_b_w  = sum(.data$n_white) / sum(.data$n_white + .data$n_black),
                        pct_black_b_w  = sum(.data$n_black) / sum(.data$n_white + .data$n_black),
                        pct_poor_total = sum(.data$n_poor)  / sum(.data$n_poor  + .data$n_other),
                        pct_poor_white = sum(.data$w_poor)  / sum(.data$w_poor  + .data$w_other),
                        dissim_racial  = sum(abs(.data$n_black / sum(.data$n_black) - .data$n_white / sum(.data$n_white))) / 2,
                        dissim_pov_tot = sum(abs(.data$n_poor  / sum(.data$n_poor)  - .data$n_other / sum(.data$n_other))) / 2,
                        dissim_pov_wht = sum(abs(.data$w_poor  / sum(.data$w_poor)  - .data$w_other / sum(.data$w_other))) / 2,
                        pop_white      = sum(.data$n_white),
                        pop_black      = sum(.data$n_black),
                        population     = sum(.data$n),
                        log_population = log(.data$population),
                        pop_poor_tot   = sum(.data$n_poor),
                        pop_poor_wht   = sum(.data$w_poor),
                        pop_other_tot  = sum(.data$n_other),
                        pop_other_wht  = sum(.data$w_other))

# tack on per-year as well as current-year county-level values ----
acy <- tidyr::pivot_wider(acr, names_from = .data$year, values_from = .data$pct_white_tot:.data$dissim_pov_wht)
acq <- dplyr::left_join(acr, acy)

# do the same thing for the pct manufacturing ----
acu <- dplyr::transmute(acs, pct_mfg = (.data$f_manuf + .data$m_manuf) / (.data$f_indus + .data$m_indus))
acv <- tidyr::pivot_wider(acu, names_from = .data$year, names_prefix = "pct_mfg_", values_from = .data$pct_mfg)
acu <- dplyr::left_join(acu, acv)

# now what about the rural-urban business? ----
dec <- dplyr::group_by(acs, .data$dd_state)
dec <- dplyr::summarise(dec)
dec <- dplyr::group_by_all(dec)
dec <- dplyr::mutate(dec,
                     urban = list(tidycensus::get_decennial("county", 
                                                            c(urban = "H002001", rural = "H002005"), 
                                                            state = dplyr::first(.data$dd_state))))
dec <- tidyr::unnest(dec)
dec <- dplyr::group_by(dec)
dec <- dplyr::select(dec, -.data$NAME)
dec <- dplyr::rename(dec, dd_county_fips = .data$GEOID)
dec <- dplyr::mutate(dec, dd_county_fips = as.numeric(.data$dd_county_fips) %% 1000)
dec <- tidyr::spread(dec, .data$variable, .data$value)
dec <- dplyr::group_by(dec, .data$dd_state, .data$dd_county_fips)
dec <- dplyr::transmute(dec, pct_urban_2010 = .data$urban / (.data$urban + .data$rural))

# staple together ----
aca <- dplyr::left_join(acq, acu)
aca <- dplyr::left_join(aca, dec)

saveRDS(aca, here::here("data", "ACS.rds"))
```


####### <!-- join together -->

```{r finish_set}
all <- dplyr::left_join(set, aca)

haven::write_dta(all, here::here("data", "cces", "CCES_with_ACS.dta"))
```
